version: '3'

services:
  postgres:
    image: postgres:10.4
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - '.env'

  redis:
    image: redis:4.0
    volumes:
      - redis:/data

  web:
    build: .
    volumes:
      - .:/imcg-app
    ports:
      - '4000:4000'
      - '1025:1025'
      - '1080:1080'
    env_file:
      - '.env'
    depends_on:
      - postgres
      - redis
    command: docker/entrypoint.sh

volumes:
  postgres:
  redis:
